### ISSUE TITLE
issue with temp files

### ISSUE THREAD

**Issue by mmeftah** [gatapia/py_ml_utils#1]
I face some issues when I run LibF(F)MClassifier : it seems there is a mistake in th save_tmp_file function, when I run .predict(test) attributes, it shows me the error : 
No such file or directory: 'tmpfiles//home/Bureau/py_ml_utils/tmpfiles/tmpqrtcWh_tmp_training_file.libfm'

there is clearly a mistake in the way above, how do you fix that ?

**Comment by gatapia** [comment]
I think this was fixed a while ago, sorry for not getting these (rarely check github)
