### ISSUE TITLE
xgboost - Python?

### ISSUE THREAD

**Issue by BrianMiner** [gatapia/py_ml_utils#2]
Thank you for these built xgboost files for windows. I was wondering once downloaded, how does the python program know how to use them? I downloaded both xgboost files here but when I run python setup.py for the python package, an error appears that I would think is easily addressed but wasn't sure how. Should this work well for the files you post? Thanks!

__builtin__.XGBoostLibraryNotFound: Cannot find XGBoost Libarary in the candicate path, did you install compilers and run build.

**Comment by gatapia** [comment]
I think pip install xgboost is fixed on Windows.  You should use that instead of this work around.
